nodeapp:
  build: ./nodeapp
  container_name: nodeapp
  net: "prom-net"
  ports:
    - "3000:3000"
    - "9090"

mongo:
  image: mongo:3
  container_name: mongo
  net: "prom-net"
  ports:
    - "27017:27017"

node_exporter:
  image: prom/node-exporter
  container_name: node-exporter
  net: "prom-net"
  ports:
    - "9100"

mongodb_exporter:
  image: lowstz/mongodb-exporter
  container_name: mongodb-exporter
  net: "prom-net"
  ports:
    - "9001"
  command: -mongodb.uri=mongodb://mongo:27017

consul:
  build: ./consul
  container_name: consul
  hostname: node1
  net: "prom-net"
  ports:
    - "8400:8400"
    - "8500:8500"
    - "8600:53/udp"
  command: -server -bootstrap -data-dir /data -ui-dir /ui

prometheus:
  build: ./prometheus
  container_name: prometheus
  net: "prom-net"
  ports:
    - "9090:9090"
