nodeapp:
  build: ./nodeapp
  ports:
    - "3000:3000"
    - "9091:9090"

mongo:
  image: mongo:3

node_exporter:
  image: prom/node-exporter

mongodb_exporter:
  image: lowstz/mongodb-exporter
  links:
    - mongo
  command: -mongodb.uri=mongodb://mongo:27017

prometheus:
  build: ./prometheus
  ports:
    - "9090:9090"
  links:
    - nodeapp
    - node_exporter:system
    - mongodb_exporter:mongo

consul:
  build: ./consul
  hostname: node1
  ports:
    - "8400:8400"
    - "8500:8500"
    - "8600:53/udp"
  command: -server -bootstrap -data-dir /data -ui-dir /ui
