nodeapp:
  build: ./nodeapp
  ports:
    - "3000:3000"
    - "9091:9090"

mongo:
  image: mongo:3

node_exporter:
  image: prom/node-exporter

prometheus:
  build: ./prometheus
  ports:
    - "9090:9090"
  links:
    - nodeapp
    - mongo
    - node_exporter:system
