# my global config
global:
  scrape_interval:     15s
  evaluation_interval: 30s
  # scrape_timeout is set to the global default (10s).

  external_labels:
    monitor: codelab

rule_files:
- "first.rules"
- "/absolute/second.rules"
- "my/*.rules"

scrape_configs:
- job_name: prometheus
  honor_labels: true
  target_groups:
  - targets: ['localhost:9090']

- job_name: node
  metrics_path: /metrics
  scheme: http
  target_groups:
  - targets: ['node-exporter:9100']

- job_name: nodeapp
  consul_sd_configs:
  - server: 'consul:8500'
  relabel_configs:
  # Ignore target services unless they are tagged in Consul with 'metrics'.
  - source_labels: ['__meta_consul_tags']
    regex:         'metrics,|,metrics,|,metrics'
    action:        keep
  # Relable the __address__ label of the service to use the service address and
  # port from Consul. By default, Prometheus will just assume the Consul agent IP
  # is correct.
  - source_labels: ['__meta_consul_service_address', '__meta_consul_service_port']
    separator:     ':'
    regex:         '(.*)'
    target_label:  '__address__'
    replacement:   '$1'

- job_name: mongo
  metrics_path: /metrics
  scheme: http
  target_groups:
  - targets: ['mongodb-exporter:9001']

- job_name: container
  metrics_path: /metrics
  scheme: http
  target_groups:
  - targets: ['container-exporter:9104']

- job_name: consul
  metrics_path: /metrics
  scheme: http
  target_groups:
  - targets: ['consul-exporter:9107']
